### ISSUE TITLE
Center events are not plotting

### ISSUE THREAD

**Issue by prybakowska** [JimboMahoney/cytofclean#14]
Hi, 
actually I have one issue, so on the plots I cannot see the events for the Center, although I can see that some events are gated out based on the %. I think it is because it is much higher on the scale? Could you tell me how to fix it? 
Paulina

**Comment by JimboMahoney** [comment]
Hi Paulina,

I'd need to investigate the FCS file to see what's really going on - it's either something to do with the detection of the "Center" events, or it's something to do with the Y axis of the plot, although both are related.

Can you upload an FCS file somewhere?

**Comment by JimboMahoney** [comment]
This should be fixed now. It was simply the estimate of the max for the Y axis on the plots.
